[package]
name = "polymesh-weights"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# substrate pallets
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }

# our pallets
pallet-corporate-actions = { path = "../corporate-actions", default-features = false }
pallet-identity = { path = "../identity", default-features = false  }
pallet-pips = { path = "../pips", default-features = false  }
pallet-portfolio = { path = "../portfolio", default-features = false  }
pallet-protocol-fee = { path = "../protocol-fee", default-features = false  }
pallet-settlement = { path = "../settlement", default-features = false  }
pallet-compliance-manager = { path = "../compliance-manager", default-features = false  }
polymesh-contracts = { path = "../contracts", default-features = false }
pallet-utility = { path = "../utility", default-features = false  }
pallet-asset = { path = "../asset", default-features = false  }
pallet-confidential = { path = "../confidential", default-features = false  }
pallet-balances = { path = "../balances", default-features = false  }

[features]
default = ["std"]
no_std = []
std = [
    "frame-support/std",
    "frame-system/std",
    "pallet-corporate-actions/std",
    "pallet-identity/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-protocol-fee/std",
    "pallet-settlement/std",
    "pallet-timestamp/std",
    "polymesh-contracts/std",
    "pallet-compliance-manager/std",
    "pallet-utility/std",
    "pallet-asset/std",
    "pallet-confidential/std",
    "pallet-balances/std",
]
