[package]
name = "polymesh-weights"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
pallet-corporate-actions = { path = "../corporate-actions", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
pallet-identity = { path = "../identity", default-features = false  }

[features]
default = ["std"]
no_std = []
std = [
    "frame-support/std",
    "pallet-corporate-actions/std",
    "pallet-timestamp/std",
    "frame-system/std",
    "pallet-identity/std"
]
