[package]
name = "pallet-group-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false}

# RPC
pallet-group-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }

# Others
serde = { version = "1.0.104", features = ["derive"] }

# Json RPC
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-blockchain = { git = 'https://github.com/PolymathNetwork/substrate', default_features = false, tag = "v2.0.1-1"}
sp-std = {git = 'https://github.com/PolymathNetwork/substrate', default_features = false, tag = "v2.0.1-1" }
sp-api = {git = 'https://github.com/PolymathNetwork/substrate', default_features = false, tag = "v2.0.1-1" }

[dev-dependencies]
substrate-test-runtime-client = { git = 'https://github.com/PolymathNetwork/substrate', default_features = false, tag = "v2.0.1-1" }
