[package]
name = "pallet-group-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false}

# RPC
pallet-group-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }

# Others
serde = { version = "1.0.104", features = ["derive"] }

# Json RPC
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-rpc = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-std = {git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8' }
sp-api = {git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8' }

[dev-dependencies]
substrate-test-runtime-client = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8' }
