[package]
name = "polymesh-runtime-testnet-v1"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Common
polymesh-common-utilities = { path = "../../common", default-features = false }
polymesh-runtime-common = { path = "../common", default-features = false}
polymesh-primitives = { path = "../../../primitives", default-features = false }

# Our pallets
pallet-protocol-fee = { path = "../../protocol-fee", default-features = false }
pallet-group = { path = "../../group", default-features = false }
pallet-identity = { path = "../../identity", default-features = false  }
pallet-balances = { path = "../../balances", default-features = false  }
pallet-asset = { path = "../../asset", default-features = false }
pallet-transaction-payment = { path = "../../transaction-payment", default-features = false  }
pallet-staking = { path = "../../staking", default-features = false  }
pallet-staking-reward-curve = { version = "2.0.0",  path = "../../staking/reward-curve", default-features = false  }
pallet-pips = { path = "../../pips", default-features = false  }
pallet-committee = { path = "../../committee", default-features = false }
pallet-multisig = { path = "../../multisig", default-features = false }
pallet-treasury = { path = "../../treasury", default-features = false }
pallet-im-online = { path = "../../im-online", default-features = false }
pallet-settlement = { path = "../../settlement", default-features = false }
pallet-group-rpc-runtime-api = { path = "../../group/rpc/runtime-api", default-features = false }
pallet-compliance-manager = { path = "../../compliance-manager", default-features = false }
pallet-statistics = { path = "../../statistics", default-features = false }
pallet-utility = { path = "../../utility", default-features = false}
pallet-contracts = { path = "../../contracts", default-features = false}
pallet-confidential = { path = "../../confidential", default-features = false }
pallet-contracts-primitives = { path = "../../contracts/common/", default-features = false}

# RPC
node-rpc-runtime-api = { path = "../../../rpc/runtime-api", default-features = false }
pallet-staking-rpc-runtime-api = { package = "pallet-staking-rpc-runtime-api", path = "../../staking/rpc/runtime-api", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { package = "pallet-protocol-fee-rpc-runtime-api", path = "../../protocol-fee/rpc/runtime-api", default-features = false }
pallet-compliance-manager-rpc-runtime-api = { package = "pallet-compliance-manager-rpc-runtime-api", path = "../../compliance-manager/rpc/runtime-api", default-features = false  }
pallet-contracts-rpc-runtime-api = { path = "../../contracts/rpc/runtime-api", default-features = false}


# Others
chrono = { version = "0.4.11", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
log = { version = "0.4.8", default-features = false }
rand = { version = "0.7.3", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
safe-mix = { version = "1.0.1", default-features = false }
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true }
serde_json = { version = "1.0.48", default-features = false }
yaml-rust = { version = "0.4.3", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-serializer = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }

pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-executive = { package = "frame-executive", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-finality-tracker = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-indices = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }

frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
ink_primitives = { git = "https://github.com/paritytech/ink", tag = "v2.1.0", default-features = false }
hex-literal = "0.2.1"

# Benchmark
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc4", optional = true }

[dev-dependencies]
test-client = { package = "substrate-test-runtime-client", git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc4" }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4"}

[features]
equalize = []
default = ["std", "equalize"]
no_std = [ 
	"pallet-confidential/no_std",
	"pallet-confidential/u64_backend",
]

only-staking = []
std = [
	"rustc-hex/std",
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-version/std",
	"sp-consensus-babe/std",
	"sp-session/std",
	"sp-authority-discovery/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-arithmetic/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"polymesh-runtime-common/std",
	"pallet-authorship/std",
	"pallet-contracts/std",
	"pallet-executive/std",
	"pallet-finality-tracker/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-group-rpc-runtime-api/std",
	"pallet-protocol-fee-rpc-runtime-api/std",
	"pallet-staking-rpc-runtime-api/std",
	"pallet-compliance-manager-rpc-runtime-api/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-settlement/std",
	"pallet-authority-discovery/std",
	"pallet-babe/std",
	"pallet-pips/std",
	"pallet-committee/std",
	"pallet-multisig/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"polymesh-common-utilities/std",
	"pallet-balances/std",
	"pallet-identity/std",
	"pallet-protocol-fee/std",
	"pallet-asset/std",
	"pallet-compliance-manager/std",
	"pallet-statistics/std",
	"pallet-asset/runtime-benchmarks",
	"pallet-confidential/std",
	"ink_primitives/std",
	"node-rpc-runtime-api/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"polymesh-runtime-common/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-committee/runtime-benchmarks",
]
