[package]
name = "polymesh-primitives"
version = "2.0.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Ours
polymesh-primitives-derive = { path = "../primitives_derive" }

# Other 
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Crypto
cryptography = { path = "../external/cryptography", default-features = false }
curve25519-dalek = { version = "2", default-features = false, features = ["nightly"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }

[dev-dependencies]
hex = { version = "^0.4.0", default-features = false }
serde_json = "1.0.48"

[features]
default = ["std"]

# Backends
u32_backend = [ "cryptography/u32_backend"]
u64_backend = [ "cryptography/u64_backend"]
avx2_backend = [ "cryptography/avx2_backend"]

no_std = [
	"cryptography/no_std"
]

std = [
	"codec/std",
	"sp-core/std",
	"serde",
	"sp-std/std",
	"sp-version/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"cryptography/std",
]
