[package]
name = "polymesh-primitives"
version = "2.0.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
chrono = {version = "0.4.18", default-features = false }

# Ours
polymesh-primitives-derive = { path = "../primitives_derive", default-features = false }

# Other
serde = { version = "1.0.104", optional = true, default-features = false, features = ["derive"] }

# Crypto
cryptography = { git = "https://github.com/PolymathNetwork/cryptography.git", branch = "substrate-2", default-features = false }
curve25519-dalek = { version = "2", default-features = false, features = ["nightly"] }
schnorrkel = { version = "0.9.1", default-features = false }
blake2 = { version = "0.9.0", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }

[dev-dependencies]
hex = { version = "^0.4.0", default-features = false }
serde_json = "1.0.48"

[features]
default = ["std"]

# Backends
u32_backend = [ "cryptography/u32_backend", "schnorrkel/u32_backend"]
u64_backend = [ "cryptography/u64_backend", "schnorrkel/u64_backend"]
avx2_backend = [ "cryptography/avx2_backend", "schnorrkel/u64_backend"]

no_std = [
    "cryptography/no_std"
]

std = [
    "chrono/std",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "serde",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",

    # Crypto
    "blake2/simd",
    "blake2/std",
    "cryptography/std",
    "curve25519-dalek/std",
    "polymesh-primitives-derive/std",
    "schnorrkel/std",
    "sp-application-crypto/std"
]

runtime-benchmarks = [
    "sp-io/disable_panic_handler",
    "sp-io/disable_oom"
]
