[package]
name = "pallet-transaction-payment"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
smallvec = "1.4.0"
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-transaction-payment-rpc-runtime-api = { version = "0.1.0", default-features = false, path = "./rpc/runtime-api" }
primitives = {package = "polymesh-primitives", default-features = false, path = "../../primitives"}

[dev-dependencies]
sp-io = { package = "sp-io", git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-balances = { package = "pallet-balances", version = "0.1.0", path = "../balances" }
polymesh-common-utilities = { package = "polymesh-common-utilities", version = "0.1.0", path = "../common" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"primitives/std",
	"pallet-transaction-payment-rpc-runtime-api/std"
]
