codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%  # allow for 5% reduction of coverage without failing

    patch: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

comment:
  layout: "diff,files"
  behavior: default
  require_changes: no

ignore:
  - "bin/**/*"
  - "**/build.rs"
