[package]
name = "node-rpc"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
node-rpc-runtime-api = { path = "./runtime-api", default-features = false }

polymesh-primitives = { path = "../primitives", default-features = false }
pallet-pips = { path = "../pallets/pips", default-features = false }
pallet-identity= { path = "../pallets/identity", default-features = false }
pallet-transaction-payment = { path = "../pallets/transaction-payment", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-core = {git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.0-rc4" }
sp-std = {git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.0-rc4" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-api = { git = 'https://github.com/paritytech/substrate', default-features = false, tag = "v2.0.0-rc4" }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', tag = "v2.0.0-rc4"}

sp-rpc = { git = 'https://github.com/paritytech/substrate', tag = "v2.0.0-rc4"}


frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4"}

# Others
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

[features]
default = ["std"]
std = [
	"node-rpc-runtime-api/std",
	"polymesh-primitives/std",
	"pallet-pips/std",
	"pallet-identity/std",
	"pallet-transaction-payment/std",
	"frame-support/std",
	"sp-core/std",
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std",
]
