[package]
name = "node-rpc"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
node-rpc-runtime-api = { path = "./runtime-api", default-features = false }

pallet-compliance-manager = { path = "../pallets/compliance-manager", default-features = false }
pallet-pips = { path = "../pallets/pips", default-features = false }
polymesh-primitives = { path = "../primitives", default-features = false }

pallet-portfolio = { path = "../pallets/portfolio", default-features = false }
pallet-identity = { path = "../pallets/identity", default-features = false }
pallet-transaction-payment = { path = "../pallets/transaction-payment", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-core = {git = 'https://github.com/PolymathNetwork/substrate', default_features = false, tag = "v2.0.1-2" }
sp-std = {git = 'https://github.com/PolymathNetwork/substrate', default_features = false, tag = "v2.0.1-2" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
sp-api = { git = 'https://github.com/PolymathNetwork/substrate', default-features = false, tag = "v2.0.1-2" }
sp-blockchain = { git = 'https://github.com/PolymathNetwork/substrate', tag = "v2.0.1-2" }
sp-rpc = { git = 'https://github.com/PolymathNetwork/substrate', tag = "v2.0.1-2" }
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }
frame-system = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-2" }

# Others
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
serde = { version = "1.0.104", optional = true, features = ["derive"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "node-rpc-runtime-api/std",
    "pallet-identity/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-transaction-payment/std",
    "polymesh-primitives/std",
    "serde",
    "sp-api/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
]
