[package]
name = "polymesh-runtime-develop"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Common
polymesh-common-utilities = { path = "../../common", default-features = false }
polymesh-runtime-common = { path = "../common", default-features = false }
polymesh-primitives = { path = "../../../primitives", default-features = false }

# Our pallets
pallet-confidential = { path = "../../confidential", default-features = false }
pallet-identity = { path = "../../identity", default-features = false }
pallet-balances = { path = "../../balances", default-features = false }
pallet-protocol-fee = { path = "../../protocol-fee", default-features = false }
pallet-utility = { path = "../../utility", default-features = false }
pallet-group = { path = "../../group", default-features = false }
pallet-asset = { path = "../../asset", default-features = false }
pallet-portfolio = { path = "../../portfolio", default-features = false  }
pallet-compliance-manager = { path = "../../compliance-manager", default-features = false }
pallet-multisig = { path = "../../multisig", default-features = false }
pallet-pips = { path = "../../pips", default-features = false }
pallet-committee = { path = "../../committee", default-features = false }
pallet-basic-sto = { path = "../../basic-sto", default-features = false }
pallet-treasury = { path = "../../treasury", default-features = false }
pallet-settlement = { path = "../../settlement", default-features = false }
pallet-im-online = { path = "../../im-online", default-features = false }
pallet-statistics = { path = "../../statistics", default-features = false }
pallet-transaction-payment = { path = "../../transaction-payment", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-staking = { path = "../../staking", default-features = false }
pallet-staking-reward-curve = { path = "../../staking/reward-curve", default-features = false }

# Others
serde = { version = "1.0.104", default-features = false }
smallvec = "1.4.0"

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
#
pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-executive = { package = "frame-executive", git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-finality-tracker = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-indices = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }

frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }

# RPC
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-group-rpc-runtime-api = { path = "../../group/rpc/runtime-api", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { path = "../../protocol-fee/rpc/runtime-api", default-features = false }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-staking-rpc-runtime-api = { path = "../../staking/rpc/runtime-api", default-features = false }
node-rpc-runtime-api = { path = "../../../rpc/runtime-api", default-features = false }

# Benchmark
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "at-add-dispatch-call", optional = true }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call"}

[features]
default = ["std", "equalize"]
equalize = []
only-staking = []
no_std = [
    "pallet-confidential/no_std",
    "pallet-confidential/u64_backend",
]
std = [
    # General
    "serde/std",
    # Polymesh
    "polymesh-runtime-common/std",
    # SP
    "codec/std",
    "sp-api/std",
    "sp-arithmetic/std",
    "sp-authority-discovery/std",
    "sp-block-builder/std",
    "sp-consensus-babe/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-staking/std",
    "sp-std/std",
    "sp-transaction-pool/std",
    "sp-version/std",

    # Frame
    "frame-support/std",
    "frame-system/std",

    # Pallets
    "pallet-asset/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "pallet-basic-sto/std",
    "pallet-committee/std",
    "pallet-compliance-manager/std",
    "pallet-confidential/std",
    "pallet-contracts-primitives/std",
    "pallet-contracts/std",
    "pallet-executive/std",
    "pallet-finality-tracker/std",
    "pallet-grandpa/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-multisig/std",
    "pallet-offences/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-protocol-fee/std",
    "pallet-randomness-collective-flip/std",
    "pallet-settlement/std",
    "pallet-staking-reward-curve/std",
    "pallet-staking/std",
    "pallet-statistics/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-treasury/std",
    "pallet-utility/std",

    # RPC
    "frame-system-rpc-runtime-api/std",
    "node-rpc-runtime-api/std",
    "pallet-contracts-rpc-runtime-api/std",
    "pallet-group-rpc-runtime-api/std",
    "pallet-protocol-fee-rpc-runtime-api/std",
    "pallet-staking-rpc-runtime-api/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-committee/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-staking/runtime-benchmarks",
    "polymesh-runtime-common/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
