[package]
name = "pallet-pips"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { path = "../common", default-features = false  }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }

pallet-group = { path = "../group", default-features = false }
pallet-identity = { path = "../identity", default-features = false }
pallet-balances = { path = "../balances", default-features = false }
pallet-treasury = { path = "../treasury", default-features = false }

# General
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }

frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }

pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-api/std",
	"sp-version/std",
	"pallet-timestamp/std",
	"frame-system/std",
	"frame-support/std",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std",
	"pallet-balances/std",
	"pallet-group/std",
	"pallet-identity/std",
	"pallet-treasury/std",
]
