version: 2
jobs:
  lint:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Check formatting
          command: ./scripts/rustfmt.sh
  test:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Build concatenated lock file for caching
          command: find . -name "Cargo.lock" -not -path "*/target/*" | xargs cat > concatenated.lock
      - run:
          name: Store rust version in a file for cache key
          command: rustc --version > rust.version
      - restore_cache:
          keys:
            - debug-cache-{{ checksum "./rust.version" }}-{{ checksum "./pallets/runtime/Cargo.lock" }}-{{ checksum "./concatenated.lock" }}
            - debug-cache-{{ checksum "./rust.version" }}-{{ checksum "./pallets/runtime/Cargo.lock" }}
            - debug-cache-{{ checksum "./rust.version" }}
            - debug-cache
      - run:
          name: runtime tests
          command: cargo test
          working_directory: ./pallets/runtime
          no_output_timeout: 60m
      - save_cache:
          key: debug-cache-{{ checksum "./rust.version" }}-{{ checksum "./pallets/runtime/Cargo.lock" }}-{{ checksum "./concatenated.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
  cli:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Build concatenated lock file for caching
          command: find . -name "Cargo.lock" -not -path "*/target/*" | xargs cat > concatenated.lock
      - run:
          name: Store rust version in a file for cache key
          command: rustc --version > rust.version
      - restore_cache:
          keys:
            - release-cache-{{ checksum "./rust.version" }}-{{ checksum "./pallets/runtime/Cargo.lock" }}-{{ checksum "./concatenated.lock" }}
            - release-cache-{{ checksum "./rust.version" }}-{{ checksum "./pallets/runtime/Cargo.lock" }}
            - release-cache-{{ checksum "./rust.version" }}
            - release-cache
      - run:
          name: Build release
          command: cargo build -j 1 --release
          no_output_timeout: 4h
      - run:
          name: cli node instance 
          command: ./target/release/polymesh --dev --pool-limit 100000 -d /tmp/pmesh-primary-node
          background: true
          no_output_timeout: 10m
      - run:
          name: cli scripts install
          command: npm install
          working_directory: ./scripts/cli
          no_output_timeout: 30m                    
      - run:
          name: cli scripts test
          command: npm test
          working_directory: ./scripts/cli
          no_output_timeout: 30m
      - save_cache:
          key: debug-cache-{{ checksum "./rust.version" }}-{{ checksum "./pallets/runtime/Cargo.lock" }}-{{ checksum "./concatenated.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
workflows:
  version: 2
  commit:
    jobs:
      - lint
      - cli
      - test
  daily-builds:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
