version: 2
jobs:
  build:
    docker:
      - image: PolymathNetwork:polymesh
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "./polymesh_substrate/Cargo.lock" }}
      - run:
          name: Init Polymesh
          command: ./init.sh
          working_directory: ./polymesh_substrate
      - run:
          name: Run cargo-check
          command: ./check.sh
          working_directory: ./polymesh_substrate
      - run:
          name: Check formatting
          command: ./scripts/rustfmt.sh
          working_directory: .
      - run:
          name: Compile everything
          command: ./build.sh
          working_directory: ./polymesh_substrate
      - run:
          name: Build release
          command: cargo build --release
          working_directory: ./polymesh_substrate
      - save_cache:
          key: dependency-cache-{{ checksum "./polymesh_substrate/Cargo.lock" }}
          paths:
            - "./polymesh_substrate/target"
            - "./polymesh_substrate/runtime/target"
            - "./polymesh_substrate/runtime/wasm/target"
