version: 2
jobs:
  lint:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Check formatting
          command: ./scripts/rustfmt.sh
          working_directory: .
  build:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "./polymesh_substrate/Cargo.lock" }}
      - run:
          name: Compile everything
          command: ./build.sh
          working_directory: ./polymesh_substrate
      - run: cargo build -p rocksdb --release
      - run:
          name: Build release
          command: cargo build --release
          working_directory: ./polymesh_substrate
      - save_cache:
          key: dependency-cache-{{ checksum "./polymesh_substrate/Cargo.lock" }}
          paths:
            - "./polymesh_substrate/target"
            - "./polymesh_substrate/runtime/target"
            - "./polymesh_substrate/runtime/wasm/target"
workflows:
  version: 2
  commit:
    jobs:
      - build
      - lint
  daily-builds:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
