version: 2
jobs:
  lint:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Check formatting
          command: ./scripts/rustfmt.sh
          working_directory: .
  build:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ checksum "./polymesh_substrate/Cargo.lock" }}
      - run:
          name: Build rocksdb
          command: cargo build -p rocksdb -j 1 --release
          working_directory: ./polymesh_substrate
      - run:
          name: Build release
          command: cargo build --release
          working_directory: ./polymesh_substrate
      - save_cache:
          key: build-cache-{{ checksum "./polymesh_substrate/Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./polymesh_substrate/target"
  test:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-cache-{{ checksum "./polymesh_substrate/runtime/Cargo.lock" }}
      - run:
          name: runtime tests
          command: cargo test
          working_directory: ./polymesh_substrate/runtime
      - save_cache:
          key: test-cache-{{ checksum "./polymesh_substrate/runtime/Cargo.lock" }}
          paths:
            - "./polymesh_substrate/runtime/target"
            - "./polymesh_substrate/runtime/wasm/target"
workflows:
  version: 2
  commit:
    jobs:
      - lint
      - build
      - test
  daily-builds:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
