[package]
name = "pallet-utility"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# General
serde = { version = "1.0.101", optional = true }

pallet-balances = { path = "../balances", default-features = false }
pallet-permissions = { path = "../permissions", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "v2.0.1", optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.1" }

# Only for benchmarks
hex-literal = "0.2.1"
hex = { version = "0.4.2", optional = true }


[features]
default = ["std"]
no_std = []
std = [
    "serde",
    "hex/std",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-io/std",
    "sp-std/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "pallet-balances/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "polymesh-common-utilities/runtime-benchmarks",
]
