[package]
name = "pallet-staking-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', default_features = false,  rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

[dev-dependencies]
serde_json = "1.0.48"

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-runtime/std",
	"frame-support/std"
]