[package]
name = "pallet-staking-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
sp-api = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-runtime = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]