[package]
name = "polymesh-runtime-identity-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath Inc. <satyam@polymath.network>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.1.2", default-features = false, features = ["derive"] }
sp-std = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-api = { git = 'https://github.com/paritytech/substrate', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
polymesh-primitives = { package = "polymesh-primitives", path = "../../../../primitives", default-features = false }
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    "serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"polymesh-primitives/std",
	"frame-support/std",
]