[package]
name = "pallet-staking"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.104", optional = true }
safe-mix = { version = "1.0.1", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499"}
sp-keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", optional = true, default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499"}
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-io = { package = "sp-io", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499"}
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-staking = { package = "sp-staking", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-session = { package = "pallet-session", features = ["historical"], git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-authorship = { package = "pallet-authorship", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
primitives = { package = "polymesh-primitives", path = "../../primitives", default-features = false }
pallet-babe = { package = "pallet-babe", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../common", default-features = false }
pallet-identity = { package = "pallet-identity", path = "../identity", default-features = false}
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }

# Optional imports for benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499", optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
test-client = { package = "substrate-test-runtime-client", git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-core = { package ="sp-core", git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-storage = { git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-balances = { package ="pallet-balances", path = "../balances" }
pallet-group = { package = "pallet-group", path = "../group"}
pallet-timestamp = { package ="pallet-timestamp", git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-staking-reward-curve = { version = "2.0.0",  path = "../staking/reward-curve" }
substrate-test-utils = { package ="substrate-test-utils", git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
chrono = { version = "0.4.11", default-features = false }
pallet-transaction-payment = { package = "pallet-transaction-payment", path = "../transaction-payment", default-features = false }
pallet-protocol-fee = { package = "pallet-protocol-fee", path = "../protocol-fee", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499"}
rand_chacha = { version = "0.2" }
parking_lot = "0.10.2"
env_logger = "0.7.1"
hex = "0.4"

[features]
default = ["std"]
std = [
	"serde",
	"safe-mix/std",
	"sp-keyring",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"primitives/std",
	"pallet-babe/std",
	"polymesh-common-utilities/std",
	"pallet-identity/std",
	"sp-application-crypto/std",
	"sp-npos-elections/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
]