[package]
name = "polymesh-runtime-common"
version = "1.0.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { path = "../../common", default-features = false }
polymesh-primitives = { path = "../../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../../primitives_derive", default-features = false }

pallet-identity = { path = "../../identity", default-features = false  }
pallet-balances = { path = "../../balances", default-features = false  }
pallet-multisig = { path = "../../multisig", default-features = false}
pallet-asset = { path = "../../asset", default-features = false }
pallet-compliance-manager = { path = "../../compliance-manager", default-features = false }
pallet-contracts = { path = "../../contracts", default-features = false }

# RPC
pallet-group-rpc-runtime-api = { path = "../../group/rpc/runtime-api", default-features = false}
pallet-settlement = { path = "../../settlement", default-features = false }

# General
serde = { version = "1.0.104", default-features = false }
rand = { version = "0.7.3", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }

pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag = "v2.0.0-rc4", optional = true }

[features]
equalize = []
only-staking = []
default = ["std", "equalize", "runtime-benchmarks"]
no_std = []
std = [
    "serde/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "pallet-identity/std",
    "pallet-balances/std",
    "pallet-multisig/std",
    "pallet-asset/std",
    "pallet-compliance-manager/std",
    "pallet-contracts/std",
    "pallet-group-rpc-runtime-api/std",
    "sp-std/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-authorship/std",
    "pallet-timestamp/std",
    "frame-benchmarking/std",
]

runtime-benchmarks = [
     "frame-benchmarking",
	"pallet-asset/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
]
