[package]
name = "pallet-statistics"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
pallet-external-agents = { path = "../external-agents", default-features = false }

# Other
serde = { version = "1.0.112", default-features = false }
serde_derive = { version = "1.0.112", optional = true, default-features = false}

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-core = { version = "2.0.1", default-features = false }
sp-io = { version = "2.0.1", default-features = false }
sp-std = { version = "2.0.1", default-features = false }
sp-api = { version = "2.0.1", default-features = false }
sp-arithmetic = { version = "2.0.1", default-features = false }
sp-runtime = { version = "2.0.1", default-features = false }

frame-support = { version = "2.0.1", default-features = false }
frame-system = { version = "2.0.1", default-features = false }

pallet-timestamp = { version = "2.0.1", default-features = false }
pallet-session = { version = "2.0.1", default-features = false }

# Only in STD
substrate-test-runtime-client = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-2", optional = true}

# Only in Benchmarks
frame-benchmarking = { version = "2.0.1", default-features = false, optional = true }

[dev-dependencies]
lazy_static = "1.4.0"

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
running-ci = []
std = [
	"substrate-test-runtime-client",
	"serde_derive",
	"codec/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"polymesh-primitives/std",
	"pallet-session/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]
