[package]
name = "polymesh-node-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/PolymathNetwork/substrate"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
polymesh-primitives = { path = "../primitives", default-features = false }
#pallet-contracts-rpc = { version = "3.0.0" }
pallet-group-rpc = { path = "../pallets/group/rpc" }
pallet-staking-rpc = { path = "../pallets/staking/rpc" }
pallet-protocol-fee-rpc = {  path = "../pallets/protocol-fee/rpc" }
node-rpc = { path = "../rpc" }

jsonrpc-core = { version = "15.0", features = ["arbitrary_precision"] }

codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-blockchain = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }
sp-api = { version = "3.0.0" }
sc-client-api = { version = "3.0.0" }
sp-consensus = { version = "0.9.0" }
sp-consensus-babe = { version = "0.9.0" }
sp-block-builder = { version = "3.0.0" }
sp-keystore = { version = "0.9.0" }

sc-rpc = { version = "3.0.0" }
sc-rpc-api = { version = "0.9.0" }
sc-chain-spec = { version = "3.0.0" }
sc-consensus-babe = { version = "0.9.0" }
sc-consensus-babe-rpc = { version = "0.9.0" }
sc-consensus-epochs = { version = "0.9.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-finality-grandpa-rpc = { version = "0.9.0" }
sc-keystore = { version = "3.0.0" }
sc-sync-state-rpc = { version = "0.9.0" }
sp-transaction-pool = { version = "3.0.0" }
substrate-frame-rpc-system = { version = "3.0.0" }
