[package]
name = "pallet-cdd-offchain-worker"
version = "2.0.0"
authors = ["Polymath Inc. <events@polymath.network>"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false}
polymesh-common-utilities = { path = "../common", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
#
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }

sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"polymesh-common-utilities/std",
	"polymesh-primitives/std",
	"codec/std",
	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-application-crypto/std",
]
