[package]
name = "pallet-compliance-manager-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { package = "polymesh-primitives", path = "../../../../primitives", default-features = false }
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../../../common", default-features = false }

# Our pallets
pallet-balances = { package = "pallet-balances", path = "../../../balances", default-features = false  }
pallet-compliance-manager = { package = "pallet-compliance-manager", path = "../../", default-features = false  }

# Others
serde = { version = "1.0.101", optional = true, features = ["derive"] }
jsonrpc-core = "14.0.5"

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.2", default-features = false, features = ["derive"] }
sp-core = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'c771821cae2dcb5a8808a19fae8122c0b9ae8499'}
sp-std = { git = 'https://github.com/paritytech/substrate.git', default_features = false, rev = 'c771821cae2dcb5a8808a19fae8122c0b9ae8499'}
sp-api = { git = 'https://github.com/paritytech/substrate', default-features = false, rev = 'c771821cae2dcb5a8808a19fae8122c0b9ae8499'}
frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, rev = 'c771821cae2dcb5a8808a19fae8122c0b9ae8499'}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    "serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"pallet-balances/std",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std",
	"frame-support/std",
]
