[package]
name = "pallet-compliance-manager-rpc"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false }
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../../common", default-features = false }

# Our pallets.
pallet-balances = { package = "pallet-balances", path = "../../balances", default-features = false  }
pallet-compliance-manager = { package = "pallet-compliance-manager", path = "../", default-features = false  }

# RPC
pallet-compliance-manager-rpc-runtime-api = { version = "0.1.0", path = "./runtime-api" }

# Other
serde = { version = "1.0.104", optional = true, features = ["derive"] }
serde_derive = { version = "1.0.104", optional = true, default-features = false  }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.2" }
sp-core = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-rpc = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-api = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}

[features]
default = ["std"]
std = [

]
