[package]
name = "pallet-staking-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-runtime = { version = "3.0.0", default_features = false }
sp-blockchain = { version = "3.0.0", default_features = false}
sp-api = { version = "3.0.0", default_features = false}

pallet-staking-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }
