[package]
name = "pallet-staking-rpc"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
serde = { version = "1.0.101", features = ["derive"] }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
sp-rpc = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-runtime = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-blockchain = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false}

pallet-staking-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }