[package]
name = "pallet-contracts"
version = "2.0.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for WASM contracts"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-contracts-primitives = { path = "common", default-features = false }
pallet-transaction-payment = { path = "../transaction-payment", default-features = false }

# General
serde = { version = "1.0.101", optional = true, features = ["derive"] }
pwasm-utils = { version = "0.12.0", default-features = false }
parity-wasm = { version = "0.41.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }
sp-runtime = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }
sp-io = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }
sp-std = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }
sp-sandbox = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }
frame-support = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }
frame-system = { git = "https://github.com/paritytech/substrate/", default-features = false, tag = "v2.0.0-rc4" }

[dev-dependencies]
wabt = "0.9.2"
assert_matches = "1.3.0"
hex-literal = "0.2.1"

[features]
default = ["std"]
no_std = []
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-sandbox/std",
	"frame-support/std",
	"frame-system/std",
	"parity-wasm/std",
	"pwasm-utils/std",
	"wasmi-validation/std",
	"pallet-contracts-primitives/std",
	"pallet-transaction-payment/std",
]
