[package]
name = "polymesh-contracts"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

[dependencies]

# Substrate specific
serde = { version = "1.0.104", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc6" }

# Polymesh specific
pallet-identity = { path = "../identity", default-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
pallet-protocol-fee = { path = "../protocol-fee", default-features = false }

[features]
default = ["std"]
no_std = []
std = [
    "serde/std",
    "sp-io/std",
    "codec/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "frame-system/std",
    "frame-support/std",
    "pallet-identity/std",
    "pallet-contracts/std",
    "polymesh-primitives/std",
    "pallet-protocol-fee/std",
    "polymesh-common-utilities/std",
]