[package]
name = "pallet-contracts"
version = "2.0.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet for WASM contracts"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
pwasm-utils = { version = "0.12.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
parity-wasm = { version = "0.41.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-runtime = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-io = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-std = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
sp-sandbox = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-support = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
frame-system = { git = "https://github.com/paritytech/substrate/", default-features = false, rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-contracts-primitives = { version = "2.0.0-rc3", default-features = false, path = "common" }
pallet-transaction-payment = { package = "pallet-transaction-payment", default-features = false, path = "../transaction-payment" }

[dev-dependencies]
wabt = "0.9.2"
assert_matches = "1.3.0"
hex-literal = "0.2.1"
pallet-balances = { package = "pallet-balances", path = "../balances" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate/", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate/", rev = "c771821cae2dcb5a8808a19fae8122c0b9ae8499" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-sandbox/std",
	"frame-support/std",
	"frame-system/std",
	"parity-wasm/std",
	"pwasm-utils/std",
	"wasmi-validation/std",
	"pallet-contracts-primitives/std",
	"pallet-transaction-payment/std",
]
