[package]
name = "node-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Our pallets
polymesh-primitives = { path = "../../primitives", default-features = false }
pallet-pips = { path = "../../pallets/pips", default-features = false }
pallet-identity = { path = "../../pallets/identity", default-features = false }
pallet-transaction-payment = { path = "../../pallets/transaction-payment", default-features = false }

# Other
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.0-rc4"}
sp-std = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.0-rc4"}
sp-runtime = { git = 'https://github.com/paritytech/substrate', default_features = false, tag = "v2.0.0-rc4"}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0-rc4"}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"polymesh-primitives/std",
	"pallet-pips/std",
	"pallet-identity/std",
	"pallet-transaction-payment/std",
]
