[package]
authors = ['Parity Technologies <admin@parity.io>']
edition = '2018'
name = 'node-template-runtime'
version = '1.0.0'

[dependencies.aura]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-aura'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.client]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-client'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.consensus]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-consensus'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.council]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-council'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.treasury]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-treasury'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.democracy]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-democracy'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.finality-tracker]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-finality-tracker'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-session'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.grandpa]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-grandpa'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.staking]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-staking'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.consensus-aura]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura-primitives'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.consensus_authorities]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-authorities'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-executive'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-indices'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-offchain-primitives'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.parity-codec]
default-features = false
features = ['derive']
version = '3.2'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.runtime-io]
default_features = false
features = ["wasm-nice-panic-message"]
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
optional = true
version = '1.0'

[dependencies.serde_derive]
optional = true
version = '1.0'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-sudo'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-version'
rev = '3e8a5e0e3e174139a1c6db447bf6cae5f900000f'

[features]
default = ['std']
std = [
    'parity-codec/std',
    'primitives/std',
    'client/std',
    'rstd/std',
    'runtime-io/std',
    'support/std',
    'balances/std',
    'executive/std',
    'aura/std',
    'indices/std',
    'primitives/std',
    'system/std',
    'council/std',
    'democracy/std',
    'treasury/std',
    'grandpa/std',
    'session/std',
    'staking/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde_derive',
    'serde',
    'safe-mix/std',
    'consensus-aura/std',
    'offchain-primitives/std',
    'consensus_authorities/std'
]
