[package]
name = "polymesh-runtime-identity-rpc"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.1.2" }
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-core = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-rpc = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
sp-api = { git = 'https://github.com/paritytech/substrate.git', default-features = false, rev = 'a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8'}
polymesh-runtime-identity-rpc-runtime-api = { version = "0.1.0", path = "./runtime-api" }
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false }