---

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: githubpr-polymesh
    type: pull-request
    webhook_token: ((polymathnetwork-polymesh-webhook-token-develop))
    source:
      repository: polymathnetwork/Polymesh
      access_token: ((github-concourse-access-token))
      base_branch: develop
      disable_forks: true
  - name: s3-polymesh
    type: s3
    source:
      bucket: polymesh-testnet-artifacts
      region_name: ca-central-1
      regexp: concourse/polymesh/polymesh-(.*)
      access_key_id: ((s3-polymath-concourse.access_key_id))
      secret_access_key: ((s3-polymath-concourse.secret_access_key))
  - name: s3-polymesh-runtime
    type: s3
    source:
      bucket: polymesh-testnet-artifacts
      region_name: ca-central-1
      regexp: concourse/polymesh-runtime/polymesh_runtime_(.*)
      access_key_id: ((s3-polymath-concourse.access_key_id))
      secret_access_key: ((s3-polymath-concourse.secret_access_key))
  - name: dockerimage-polymesh
    type: docker-image
    source:
      repository: 414255671868.dkr.ecr.us-east-1.amazonaws.com/polymathnetwork/polymesh
      aws_access_key_id: ((polymath-ecr.aws-access-id))
      aws_secret_access_key: ((polymath-ecr.aws-access-secret))
  - name: semver-git-polymesh
    type: semver
    source:
      driver: git
      uri: git@github.com:polymathnetwork/concourse-semver-tracking
      branch: master
      file: polymesh/alcyone-version
      private_key: ((github-polymathnetwork-concourse-semver-tracking.id_rsa))

jobs:
  - name: build-polymesh
    plan:
      - get: githubpr-polymesh
        params:
          list_changed_files: true
        trigger: true
        version: every
        params:
          integration_tool: merge
      - put: githubpr-polymesh-put
        resource: githubpr-polymesh
        params:
          path: githubpr-polymesh
          status: pending
        get_params:
          skip_download: true
      - load_var: scmpr
        file: githubpr-polymesh/.git/resource/pr
      - load_var: scmheadsha
        file: githubpr-polymesh/.git/resource/head_sha
      - load_var: rusttoolchain
        file: githubpr-polymesh/rust-toolchain
      - get: semver-git-polymesh
        params:
          pre: developpr((.:scmpr)).((.:scmheadsha))
          pre_without_version: true
      - in_parallel:
          - task: run-lint
            config:
              inputs:
                - name: githubpr-polymesh
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: polymathnetwork/rust
                  tag: debian-1.45.0-((.:rusttoolchain))
                  aws_access_key_id: ((polymath-ecr.aws-access-id))
                  aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                  aws_region: us-east-1
              run:
                dir: githubpr-polymesh
                path: bash
                args: [".concourse/scripts/t-rustfmt-lint.sh"]
          - task: cargo-build
            params:
              SUBMODULE_ACCESS_TOKEN: ((github-concourse-access-token))
            config:
              inputs:
                - name: githubpr-polymesh
                - name: semver-git-polymesh
              caches:
                - path: githubpr-polymesh/target
                - path: /usr/local/cargo
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: polymathnetwork/rust
                  tag: debian-1.45.0-((.:rusttoolchain))
                  aws_access_key_id: ((polymath-ecr.aws-access-id))
                  aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                  aws_region: us-east-1
              run:
                path: bash
                args: ["githubpr-polymesh/.concourse/scripts/t-cargo-build.sh", "githubpr-polymesh", "artifact", "semver-git-polymesh"]
              outputs:
                - name: artifact
          - task: npm-install
            config:
              inputs:
                - name: githubpr-polymesh
              caches:
                - path: githubpr-polymesh/scripts/cli/node_modules
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: polymathnetwork/node
                  tag: 12
                  aws_access_key_id: ((polymath-ecr.aws-access-id))
                  aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                  aws_region: us-east-1
              run:
                path: bash
                args: ["githubpr-polymesh/.concourse/scripts/t-npm-install.sh", "githubpr-polymesh", "npm-caches"]
              outputs:
                - name: npm-caches
      - in_parallel:
          - task: clippy-test
            params:
              SUBMODULE_ACCESS_TOKEN: ((github-concourse-access-token))
            config:
              inputs:
                - name: githubpr-polymesh
              caches:
                - path: githubpr-polymesh/target
                - path: /usr/local/cargo
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: polymathnetwork/rust
                  tag: debian-1.45.0-((.:rusttoolchain))
                  aws_access_key_id: ((polymath-ecr.aws-access-id))
                  aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                  aws_region: us-east-1
              run:
                path: bash
                args: ["githubpr-polymesh/.concourse/scripts/t-clippy-test.sh", "githubpr-polymesh"]
          - task: cargo-test
            params:
              SUBMODULE_ACCESS_TOKEN: ((github-concourse-access-token))
            config:
              inputs:
                - name: githubpr-polymesh
              caches:
                - path: githubpr-polymesh/target
                - path: /usr/local/cargo
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: polymathnetwork/rust
                  tag: debian-1.45.0-((.:rusttoolchain))
                  aws_access_key_id: ((polymath-ecr.aws-access-id))
                  aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                  aws_region: us-east-1
              run:
                path: bash
                args: ["githubpr-polymesh/.concourse/scripts/t-cargo-test.sh", "githubpr-polymesh"]
          - task: integration-test
            config:
              inputs:
                - name: githubpr-polymesh
                - name: artifact
                - name: npm-caches
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: polymathnetwork/node
                  tag: 12
                  aws_access_key_id: ((polymath-ecr.aws-access-id))
                  aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                  aws_region: us-east-1
              run:
                path: bash
                args: ["githubpr-polymesh/.concourse/scripts/t-npm-test.sh", "githubpr-polymesh", "npm-caches", "artifact"]
      - in_parallel:
          - put: s3-polymesh
            params:
              file: artifact/polymesh-*
              acl: public-read
          - put: s3-polymesh-runtime
            params:
              file: artifact/polymesh_runtime_develop-*
              acl: public-read
          - put: s3-polymesh-runtime
            params:
              file: artifact/polymesh_runtime_testnet-*
              acl: public-read
          - put: dockerimage-polymesh
            params:
              build: artifact
              dockerfile: artifact/Dockerfile.distroless
              tag_file: artifact/tag_file
              tag_prefix: distroless-
              additional_tags: artifact/additional_tags.distroless
          - put: dockerimage-polymesh
            params:
              build: artifact
              dockerfile: artifact/Dockerfile.debian
              tag_file: artifact/tag_file
              tag_prefix: debian-
              additional_tags: artifact/additional_tags.debian
      - put: githubpr-polymesh
        params:
          path: githubpr-polymesh
          status: success
    on_failure:
      do:
        - get: githubpr-polymesh-meta
          resource: githubpr-polymesh
          params:
            integration_tool: checkout
        - put: githubpr-polymesh
          params:
            path: githubpr-polymesh-meta
            status: failure
          get_params:
            skip_download: true
    on_error:
      put: githubpr-polymesh
      params:
        path: githubpr-polymesh
        status: error
      get_params:
        skip_download: true

