name: Publish docs

on:
  push:
    branches:
      - develop

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-09-28
        target: wasm32-unknown-unknown
        override: true
        default: true
    - name: Build docs
      run: cargo doc --no-deps --workspace --release --verbose --exclude node-bench --exclude node-testing
    - name: Add index file
      run: echo "<html lang='en'><head><meta http-equiv='refresh' content='0; URL=./polymesh/index.html'></head></html>" > ./target/doc/index.html
    - name: Publish to Cloudflare workers
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
