name: Update Polymesh.json

on:
  push:
    branches:
    - develop
    paths:
    - 'polymesh_schema.json'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Get Branch Name
      run: echo "##[set-env name=BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Copy polymesh_schema
      run: cp polymesh_schema.json ..
    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: PolymathNetwork/Polymesh-Issuer
        ref: 'develop'
        token: ${{ secrets.GH_TOKEN }}
    - name: Copy polymesh_schema.json into Repo
      run: cp ../polymesh_schema.json ./src/sdk/specs/polymesh.json
    - name: Commit Code
      run: |
        git config --global user.name 'Github'
        git config --global user.email 'fahdw@users.noreply.github.com'
        git add .
        git commit -m "update polymesh_schema"
        git push origin develop
